version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    target-branch: "automatic-version-bumps"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    target-branch: "automatic-version-bumps"
