version: 2

build:
  os: ubuntu-22.04
  tools:
    # 3.13 breaks pathlib.Path docs; see https://github.com/sphinx-doc/sphinx/issues/13178
    python: "3.12"
  apt_packages:
    - tree
  jobs:
    post_create_environment:
      # Installing doesn't work; the wrong target is used even with 'virtualenvs.create false'. There is a GitHub issue
      # which may be a better solution in the future: https://github.com/python-poetry/poetry/issues/1937
      - curl -sSL https://install.python-poetry.org | POETRY_VERSION=2.1.3 python -
      - $HOME/.local/bin/poetry self add poetry-plugin-export
      - $HOME/.local/bin/poetry export --only=main,docs,manual-extras --all-extras --without-hashes --output=requirements-from-poetry.txt
      - cat requirements-from-poetry.txt

    pre_build:
      - pip list
    #   - python -m sphinx -b linkcheck docs/ _build/linkcheck  # Fails for valid GitHub links?

python:
  install:
    - requirements: requirements-from-poetry.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

formats:
  - pdf

submodules:
  include: all