["`data.csv.zip`"]
label = "`data.csv.zip`"
path = "data/data.csv.zip"
index = "timestamp"
description = """
Written by `to_csv()`.

This is a multiline description. The dataset has `shape=(1500, 4)` and is located at path=`'data/data.csv.zip'`.
"""

["`data.json.zip`"]
label = "`data.json.zip`"
path = "data/data.json.zip"
index = "timestamp"
description = """
Written by `to_json()`.

This is a multiline description. The dataset has `shape=(1500, 4)` and is located at path=`'data/data.json.zip'`.
"""

["`data.parquet.zip`"]
label = "`data.parquet.zip`"
path = "data/data.parquet.zip"
index = "timestamp"
description = """
Written by `to_parquet()`.

This is a multiline description. The dataset has `shape=(1500, 4)` and is located at path=`'data/data.parquet.zip'`.
"""

["`data.feather.zip`"]
label = "`data.feather.zip`"
path = "data/data.feather.zip"
index = "timestamp"
description = """
Written by `to_feather()`.

This is a multiline description. The dataset has `shape=(1500, 4)` and is located at path=`'data/data.feather.zip'`.
"""
